generation_config:
    temperature: 0.5
    top_p: 0.95
    top_k: 50
    num_beams: 1
    use_cache: True
    repetition_penalty: 1.2
    max_new_tokens: 1024
    do_sample: True
    eos_token_id: 0
    bos_token_id: 0
    pad_token_id: 0
